/* tslint:disable */
/* eslint-disable */
/**
 * Matrix Routing OSM
 * With the Matrix Routing OSM service you can compute distances and travel times between a set of origins and destinations based on open street map data.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Options
 */
export interface Options {
    /**
     * Defines the average detour an actual route on the road requires, compared to the direct distance.
     * This factor is used to estimate by direct distance a relation that could not be calculated using the road network.
     * If not specified, the factor is selected based on the profile.
     * @type {number}
     * @memberof Options
     */
    detourFactor?: number;
    /**
     * Defines the average speed of the vehicle.
     * This parameter is used to calculate the travel time for a relation that could not be calculated using the road network.
     * If not specified, the average speed is selected based on the profile.
     * @type {number}
     * @memberof Options
     */
    averageSpeed?: number;
}

/**
 * Check if a given object implements the Options interface.
 */
export function instanceOfOptions(value: object): value is Options {
    return true;
}

export function OptionsFromJSON(json: any): Options {
    return OptionsFromJSONTyped(json, false);
}

export function OptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Options {
    if (json == null) {
        return json;
    }
    return {
        
        'detourFactor': json['detourFactor'] == null ? undefined : json['detourFactor'],
        'averageSpeed': json['averageSpeed'] == null ? undefined : json['averageSpeed'],
    };
}

export function OptionsToJSON(value?: Options | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'detourFactor': value['detourFactor'],
        'averageSpeed': value['averageSpeed'],
    };
}

